### ISSUE TITLE
configurar en el archivo urls.py para que funcione la destinación de las paginas

### ISSUE THREAD

**Issue by valentinalbornozz** [CodeSystem2022/Chaskibunes2023---Tercer-Semestre#37]
Dale la logica al proyecto en views para que se pueda ver una vez ejecutemos el comando python manage.py runserver

**Comment by G4llegus** [comment]
Se añade la funcionalidad url con sus respectivos imports para su función con las paginas

**Comment by kevinAleFunes** [comment]
Actualizamos y conectamos a la base de datos.
